name: Run Pytest and Check Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=fake;AccountKey=fake;EndpointSuffix=core.windows.net"
      APPINSIGHTS_CONNECTION_STRING: "InstrumentationKey=fake-uuid;IngestionEndpoint=https://fake.endpoint.com"
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=fake-uuid;IngestionEndpoint=https://fake.endpoint.com"
      CONTENT_SAFETY_ENDPOINT: "https://fake.endpoint.com"
      CONTENT_SAFETY_KEY: "fake-key"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Switch to Current Branch
      run: git checkout ${{ env.BRANCH }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        # Dodaj brakujące zależności
        pip install opencensus-ext-azure
        pip install -e .

    - name: Run tests with coverage
      run: |
        export PYTHONPATH="${PYTHONPATH}:./src"
        pytest --cov=src --cov-fail-under=1