name: Run Pytest and Check Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      AZURE_OPENAI_API_KEY: "fake-openai-key"
      AZURE_OPENAI_ENDPOINT: "https://fake-openai-endpoint.openai.azure.com"
      AZURE_OPENAI_DEPLOYMENT: "fake-deployment"
      AZURE_OPENAI_MODEL: "gpt-4"
      API_VERSION: "2024-06-01"

      AZURE_SPEECH_API_KEY: "fake-speech-key"
      AZURE_SPEECH_REGION: "eastus"

      ELEVENLABS_API_KEY: "sk-fake-elevenlabs"

      APPINSIGHTS_CONNECTION_STRING: "InstrumentationKey=fake-uuid;IngestionEndpoint=https://fake.endpoint.com"

      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=fake;AccountKey=fake;EndpointSuffix=core.windows.net"

      CONTENT_SAFETY_ENDPOINT: "https://fake-safety-endpoint"
      CONTENT_SAFETY_KEY: "fake-safety-key"

      AZURE_KEYVAULT_URL: "https://fake-vault.vault.azure.net"

      ELEVENLABS_PASSWORD: "Fakepassword123"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Switch to Current Branch
      run: git checkout ${{ env.BRANCH }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        pip install opencensus-ext-azure
        pip install -e .


    - name: Run tests with coverage
      run: |
        export PYTHONPATH="${PYTHONPATH}:./src"
        pytest --cov=src --cov-fail-under=70
